spring:
  datasource:
    url: jdbc:mysql://localhost:3306?serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:/dataImpl/*/*MapperImpl.xml

server:
  port: 8082