spring:
  datasource:
     url: jdbc:mysql://localhost:3306/nkg?serverTimezone=GMT%2B8&characterEncoding=UTF-8
     username: root
     password: ""
     driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
     cache: false
  jackson:
    time-zone: GMT+8


mybatis:
  mapper-locations: classpath*:/dataImpl/*/*MapperImpl.xml

server:
  port: 8082